In [2]:
import matplotlib.pyplot as plt
from utils.datasets import load_dataset

In [14]:
loaders = load_dataset('qm9xas', 256, [0.8, 0.1, 0.1], standardize='normal')
transform = loaders['transform']
data = loaders['loader_trn'].dataset.data
print(data.shape)
print(data.mean(0), data.std(0))

t_data = transform.inverse(data)
print(t_data.shape)
print(t_data.mean(0), t_data.std(0))

torch.Size([44800, 100])
tensor([ 3.1721e-18,  1.8239e-18, -3.9651e-18, -4.0444e-18, -4.0444e-18,
         1.1102e-18, -4.4409e-18,  6.0269e-18, -8.9611e-18,  2.8707e-17,
         1.4592e-17, -2.4108e-17, -2.2204e-18, -6.3441e-19, -4.6312e-17,
        -9.3259e-17,  5.1546e-17,  2.0618e-18,  2.4028e-17,  6.4552e-17,
        -6.5900e-17,  1.3846e-16, -4.9365e-18, -1.4845e-16, -9.7065e-17,
         1.6431e-16, -1.4528e-16, -2.2775e-16, -6.9785e-17, -2.8549e-16,
        -1.6368e-16, -1.4528e-16, -5.5067e-16,  2.9183e-17,  8.5011e-17,
         6.7248e-17, -3.1848e-16,  4.6947e-17,  2.9944e-16, -1.3767e-16,
        -1.9603e-16, -3.2799e-16, -4.4441e-16, -7.6447e-17,  8.1205e-17,
         2.2204e-18, -3.9809e-16,  2.4108e-17, -3.2942e-16, -3.6162e-16,
         5.3132e-17,  3.7938e-16,  7.2640e-17,  9.1038e-17, -2.8168e-16,
        -1.0595e-16, -2.4552e-16,  2.3346e-16, -3.8858e-16, -2.8802e-16,
        -8.9452e-17, -4.3394e-16,  3.6193e-16, -3.6066e-16, -3.1181e-16,
         2.1887e-16, -5.76

In [15]:
loaders = load_dataset('qm9xas', 256, [0.8, 0.1, 0.1], standardize='lognormal')
transform = loaders['transform']
data = loaders['loader_trn'].dataset.data
print(data.shape)
print(data.mean(0))
print(data.std(0))

t_data = transform.inverse(data)
print(t_data.shape)
print(t_data.mean(0))
print(t_data.std(0))

torch.Size([100])
torch.Size([44800, 100])
tensor([ 4.9372e-15, -2.3797e-15,  1.3670e-15,  8.1776e-16,  6.8231e-16,
        -3.4258e-16, -1.1824e-16, -2.9754e-16,  1.7288e-17,  2.6629e-16,
        -2.7216e-16,  1.3005e-17,  1.4909e-17, -9.3893e-17, -1.7129e-17,
         2.2839e-17, -1.7129e-17,  1.4909e-17,  8.1363e-17, -2.4901e-17,
        -4.6384e-16, -4.3735e-17,  4.6756e-16,  6.4552e-17, -3.9873e-16,
         2.9500e-16,  7.3655e-16,  8.5868e-16, -3.8699e-16,  9.2942e-17,
        -2.8295e-16,  6.9849e-16, -2.1316e-16, -1.1429e-15,  5.2973e-17,
        -4.7518e-16,  2.4996e-16,  6.6613e-16, -2.4520e-16, -6.8517e-17,
        -6.0618e-16, -3.8033e-16, -2.7946e-16,  8.2188e-16,  5.9318e-16,
        -3.4131e-16, -3.7748e-17, -8.1934e-16,  1.6780e-16, -9.6526e-16,
        -1.2758e-15,  9.8778e-16,  8.2093e-16, -6.0174e-16, -9.5352e-16,
         5.7510e-16,  8.0063e-16, -1.9381e-16, -6.8073e-16, -6.8961e-16,
        -5.8461e-16,  1.5543e-17,  8.5107e-16, -3.2514e-16,  2.0523e-16,
        

In [12]:
import torch
a = torch.ones(1, 100)
transform.inverse(transform.forward(a))

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]], dtype=torch.float64)